Enable SL/TP
dydxprotocol/v4-native-android pull request #140
Opened 2024-06-04 22:15 UTC by ruixhuang

2024-06-05 23:59 UTC, prashanDYDX approved these changes

2024-06-05 23:59 UTC, prashanDYDX commented on v4/integration/dydxStateManager/src/main/java/exchange/dydx/dydxstatemanager/AbacusStateManager.kt
> +                default = true,
wait this is a big change right? did we mean to do this?

2024-06-06 00:00 UTC, prashanDYDX requested changes
want to know whether the abacus v2 change was intentional

2024-06-06 01:11 UTC, ruixhuang commented
> want to know whether the abacus v2 change was intentional

Yes, SL/TP was coded/tested with V2 turned on, so we should start using V2 and deprecate V1.

2024-06-14 17:34 UTC, prashanDYDX approved these changes

2024-06-14 17:35 UTC, merged